name: mtbmtbmtb
favicon: null
layout_spectrum: 0.47284256131388247
typography_spectrum: 0.27370150410570204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3952845335006714
  lightness: 0.008220289833843708
  saturation: 0.11745564499869943
  rhythmicContrast: 0.10948508814908564
purpose: []
